import { redirect } from "next/navigation";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth-options";
import { connectToDatabase } from "@/lib/db";
import { ContentDraft } from "@/lib/models/content-draft";
import Link from "next/link";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { PageHeader } from "@/components/admin/page-header";

type SearchParams = Promise<{ q?: string; page?: string }>;
const PAGE_SIZE = 20;

export default async function WorkflowRunsPage({ searchParams }: { searchParams: SearchParams }) {
  const session = await getServerSession(authOptions);
  if (!session) redirect("/admin/login");

  const { q, page } = await searchParams;
  const pageNum = Math.max(1, Number(page || "1"));

  const db = await connectToDatabase();

  const match: any = { workflowRunId: { $exists: true, $ne: null } };
  if (q) {
    match.$or = [
      { workflowRunId: { $regex: q, $options: "i" } },
      { workflowKey: { $regex: q, $options: "i" } },
      { promptKey: { $regex: q, $options: "i" } },
    ];
  }

  const grouped = db
    ? await ContentDraft.aggregate([
        { $match: match },
        {
          $group: {
            _id: "$workflowRunId",
            workflowKey: { $first: "$workflowKey" },
            createdAt: { $min: "$createdAt" },
            updatedAt: { $max: "$updatedAt" },
            steps: { $sum: 1 },
            maxStepIndex: { $max: "$workflowStepIndex" },
          },
        },
        { $sort: { updatedAt: -1 } },
        { $skip: (pageNum - 1) * PAGE_SIZE },
        { $limit: PAGE_SIZE },
      ])
    : [];

  const totalRuns = db
    ? await ContentDraft.aggregate([
        { $match: match },
        { $group: { _id: "$workflowRunId" } },
        { $count: "count" },
      ])
    : [];

  const total = totalRuns[0]?.count || 0;
  const totalPages = Math.max(1, Math.ceil(total / PAGE_SIZE));

  const pageLink = (target: number) => {
    const params = new URLSearchParams();
    if (q) params.set("q", q);
    params.set("page", String(target));
    return `?${params.toString()}`;
  };

  return (
    <div className="admin-page-stack space-y-6 pb-8 w-full">
      <PageHeader
        title="Workflow Runs"
        subtitle="Grouped runs generated by the AI workflow engine."
        breadcrumb={[{ label: "Dashboard", href: "/admin/dashboard" }, { label: "Workflow Runs" }]}
      />

      <Card className="admin-card rounded-xl">
        <CardContent className="pt-6">
          <form className="flex gap-2">
            <input
              name="q"
              defaultValue={q || ""}
              placeholder="Search by run id, workflow key, prompt key"
              className="h-10 flex-1 rounded-lg border border-slate-200 px-3 text-sm"
            />
            <button className="h-10 rounded-lg bg-slate-900 px-4 text-white text-sm font-medium">Search</button>
          </form>
        </CardContent>
      </Card>

      <Card className="admin-card rounded-xl overflow-hidden">
        <CardHeader className="pb-2">
          <CardTitle className="text-base font-semibold">Recent Runs</CardTitle>
        </CardHeader>
        <CardContent className="p-0">
          <div className="overflow-x-auto">
            <table className="w-full text-left border-collapse">
              <thead>
                <tr className="bg-slate-50">
                  <th className="px-4 py-3 text-xs font-semibold text-slate-500 uppercase tracking-wide">Run ID</th>
                  <th className="px-4 py-3 text-xs font-semibold text-slate-500 uppercase tracking-wide">Workflow</th>
                  <th className="px-4 py-3 text-xs font-semibold text-slate-500 uppercase tracking-wide">Steps</th>
                  <th className="px-4 py-3 text-xs font-semibold text-slate-500 uppercase tracking-wide">Status</th>
                  <th className="px-4 py-3 text-xs font-semibold text-slate-500 uppercase tracking-wide">Updated</th>
                  <th className="px-4 py-3 text-xs font-semibold text-slate-500 uppercase tracking-wide text-right">Action</th>
                </tr>
              </thead>
              <tbody>
                {grouped.map((run: any) => {
                  const expectedSteps = Number.isFinite(Number(run.maxStepIndex)) ? Number(run.maxStepIndex) + 1 : Number(run.steps || 0);
                  const isComplete = Number(run.steps || 0) >= expectedSteps;
                  return (
                  <tr key={run._id} className="border-b border-slate-100 hover:bg-slate-50">
                    <td className="px-4 py-3 text-sm font-medium text-slate-900">{run._id}</td>
                    <td className="px-4 py-3 text-sm text-slate-700">{run.workflowKey || "-"}</td>
                    <td className="px-4 py-3 text-sm text-slate-700">{run.steps}</td>
                    <td className="px-4 py-3">
                      <span
                        className={`rounded-full px-2.5 py-1 text-xs font-semibold ${
                          isComplete
                            ? "bg-emerald-100 text-emerald-700"
                            : "bg-amber-100 text-amber-700"
                        }`}
                      >
                        {isComplete ? "Complete" : "Partial"}
                      </span>
                    </td>
                    <td className="px-4 py-3 text-sm text-slate-500">{run.updatedAt ? new Date(run.updatedAt).toLocaleString() : ""}</td>
                    <td className="px-4 py-3 text-right">
                      <Link
                        href={`/admin/workflow-runs/${run._id}`}
                        className="inline-flex h-8 items-center rounded-lg border border-slate-200 px-3 text-sm text-slate-700 hover:bg-slate-50"
                      >
                        View
                      </Link>
                    </td>
                  </tr>
                )})}
              </tbody>
            </table>
          </div>

          {grouped.length === 0 ? <div className="p-10 text-center text-sm text-slate-500">No runs found.</div> : null}
        </CardContent>
      </Card>

      <div className="flex items-center justify-between gap-2">
        <p className="text-sm text-slate-500">
          Showing {total === 0 ? 0 : (pageNum - 1) * PAGE_SIZE + 1}-{Math.min(pageNum * PAGE_SIZE, total)} of {total}
        </p>
        <div className="flex gap-2">
          <Link href={pageLink(Math.max(1, pageNum - 1))} className={`inline-flex h-9 items-center rounded-lg border border-slate-200 px-3 text-sm ${pageNum === 1 ? "pointer-events-none opacity-50" : ""}`}>
            Prev
          </Link>
          <Link href={pageLink(Math.min(totalPages, pageNum + 1))} className={`inline-flex h-9 items-center rounded-lg border border-slate-200 px-3 text-sm ${pageNum === totalPages ? "pointer-events-none opacity-50" : ""}`}>
            Next
          </Link>
        </div>
      </div>
    </div>
  );
}

